#
#Fri Dec 05 14:39:28 COT 2025
chrome.switches=--start-maximized, --disable-popup-blocking, --disk-cache-dir\=null, --ignore-certificate-errors, --disable-download-notification
browserName=chrome
version=
platform=ANY
