#
#Mon Aug 25 16:22:44 COT 2025
app=D\:\\Auto\\Cmax_CompraPaquetes/src/test/resources/app/phone.apk
appPackage=com.google.android.dialer
deviceScreenSize=720x1612
orientation=PORTRAIT
appiumVersion=1.22.3
sessionName=Cmax_CompraPaquetes
autoDismissAlerts=true
deviceName=ZT322M2KRX
platform=LINUX
deviceUDID=ZT322M2KRX
appActivity=.activities.CallLogActivity
chromedriverExecutable=src/test/resources/webdriver/windows/chromedriver.exe
hub=http\://127.0.0.1\:4723/wd/hub
platformVersion=14
automationName=UiAutomator2
reset=false
captureScreenshots=true
deviceModel=moto g24
deviceOrientation=portrait
deviceManufacturer=motorola
platformName=Android
